version: '3'
services:
  neocapy:
    container_name: neocapy
    build:
      dockerfile: ./Dockerfile
      context: ./
    restart: unless-stopped
    environment:
      MATRIX_USER: ""
      MATRIX_PASSWORD: ""
      MATRIX_ROOM_ID: ""
      MATRIX_SERVER: "https://matrix.org"

      CAPY_LIFE_LINK: "https://capy.life"
      CAPY_API_LINK: "https://capy.life/api/"

      MONGO_IP: "neocapy_mongodb"
      MONGO_PORT: 27017
      MONGO_DB: "neocapy"
    depends_on:
      - mongodb
    networks:
      - backend

  mongodb:
    image: mongo
    container_name: neocapy_mongodb
    restart: unless-stopped
    environment:
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - mongodbdata:/data/db
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  mongodbdata:
    driver: local
